    install.packages("markdown")
    install.packages("tinytex")
    install.packages("tidyverse")
    install.packages("flextable")
    install.packages("remotes")
    remotes::install_github(repo = "speegled/fosdata")
